- name: Install and start Apache Server
  hosts: "{{ variable_host | default('node1') }}"
  become: yes
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest
    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: true
